### ISSUE TITLE
Issue: exec argocd-repo-server failed: Permission denied

### ISSUE THREAD

**Issue by gogovan-vincentngai** [camptocamp/docker-argocd#10]
Hi 
I need helm and sops support in my argocd , i know there have release for v2.0 now 
But i just need to try so i try 1.8.5 version 

I try using the same  **Dockerfile** and **argocd-repo-server-wrapper**  and then upload to our own docker repo
I am using back 1.8.5 install script from argo https://raw.githubusercontent.com/argoproj/argo-cd/v1.8.6/manifests/install.yaml
and modify the repo-sever image

However it turn to CrashLoopBackOff with below error logs
[FATAL tini (7)] exec argocd-repo-server failed: Permission denied

But when i using directly from camptocamp image without change other setting , its is fine 
    repository: "camptocamp/argocd"
    tag: "v1.8.5_c2c.1"

so i wonder something is missing from the **Dockerfile** or the **argocd-repo-server-wrapper**

Anyone can help

**Comment by tanandy** [comment]
for your information, im already using this with 1.8.7 and its working.

```
FROM golang:1.15 as builder
RUN git clone --branch=20200403-1 --depth=1 https://github.com/camptocamp/helm-sops && \
    cd helm-sops && \
    go build

FROM argoproj/argocd:v1.8.7
USER root
COPY argocd-repo-server-wrapper /usr/local/bin/
COPY --from=builder /go/helm-sops/helm-sops /usr/local/bin/
RUN cd /usr/local/bin && \
    mv argocd-repo-server _argocd-repo-server && \
    mv argocd-repo-server-wrapper argocd-repo-server && \
    chmod +x argocd-repo-server && \
    mv helm _helm && \
    mv helm2 _helm2 && \
    mv helm-sops helm && \
    ln helm helm2
USER argocd
```

wrapper (using k8s projected volumes):
```
#! /bin/sh

GPG_KEYS_DIR=/var/secrets

if [ -d ${GPG_KEYS_DIR} ]
then
    for file in $GPG_KEYS_DIR/*
    do
        gpg --quiet --import $file
    done
fi

exec "$(dirname "$0")/_$(basename "$0")" "$@"
```

**Comment by gogovan-vincentngai** [comment]
> for your information, im already using this with 1.8.7 and its working.
> 
> ```
> FROM golang:1.15 as builder
> RUN git clone --branch=20200403-1 --depth=1 https://github.com/camptocamp/helm-sops && \
>     cd helm-sops && \
>     go build
> 
> FROM argoproj/argocd:v1.8.7
> USER root
> COPY argocd-repo-server-wrapper /usr/local/bin/
> COPY --from=builder /go/helm-sops/helm-sops /usr/local/bin/
> RUN cd /usr/local/bin && \
>     mv argocd-repo-server _argocd-repo-server && \
>     mv argocd-repo-server-wrapper argocd-repo-server && \
>     chmod +x argocd-repo-server && \
>     mv helm _helm && \
>     mv helm2 _helm2 && \
>     mv helm-sops helm && \
>     ln helm helm2
> USER argocd
> ```
> 
> wrapper (using k8s projected volumes):
> 
> ```
> #! /bin/sh
> 
> GPG_KEYS_DIR=/var/secrets
> 
> if [ -d ${GPG_KEYS_DIR} ]
> then
>     for file in $GPG_KEYS_DIR/*
>     do
>         gpg --quiet --import $file
>     done
> fi
> 
> exec "$(dirname "$0")/_$(basename "$0")" "$@"
> ```

Works for me 
So the orginal Dockerfile is missing the line
```chmod +x argocd-repo-server && \```

And after adding 
 ```
       env:
        - name: ARGOCD_BINARY_NAME
          value: "argocd-repo-server"
```

to repo-server 

it also working in 2.0.0 version

Thanks @tanandy

**Comment by gogovan-vincentngai** [comment]
not sure ask here is correct or not 
@tanandy  do you know how i can use Vault as backend ?

I try follow this https://github.com/jkroepke/helm-secrets#change-secret-driver
add below to repo-server
```
env:
        - name: VAULT_ADDR 
          value: "https://VaultADD"
        - name: VAULT_TOKEN
          value: "myVaultToken"
        - name: HELM_SECRETS_DRIVER
          value: "vault"  
```

But seems not works 

I confirm the  VAULT_ADDR and  VAULT_TOKEN are work correctly in my local 

Error 
```
 failed exit status 1: [helm-sops] Error: failed to decrypt secret file 'secrets.yaml': No keys found in file
```

**Comment by tanandy** [comment]
> not sure ask here is correct or not
> @tanandy do you know how i can use Vault as backend ?
> 
> I try follow this https://github.com/jkroepke/helm-secrets#change-secret-driver
> add below to repo-server
> 
> ```
> env:
>         - name: VAULT_ADDR 
>           value: "https://VaultADD"
>         - name: VAULT_TOKEN
>           value: "myVaultToken"
>         - name: HELM_SECRETS_DRIVER
>           value: "vault"  
> ```
> 
> But seems not works
> 
> I confirm the VAULT_ADDR and VAULT_TOKEN are work correctly in my local
> 
> Error
> 
> ```
>  failed exit status 1: [helm-sops] Error: failed to decrypt secret file 'secrets.yaml': No keys found in file
> ```

Honestly, we dont use helm secrets a lot these days since the deprecation, plus the secret is written to the fs

We prefer to rely on helm sops that is basically supporting lot of things (gpg, kms, vault...). You have the example on how we use helm sops above ;) with projected volume

https://github.com/mozilla/sops#encrypting-using-hashicorp-vault

**Comment by gogovan-vincentngai** [comment]
> > not sure ask here is correct or not
> > @tanandy do you know how i can use Vault as backend ?
> > I try follow this https://github.com/jkroepke/helm-secrets#change-secret-driver
> > add below to repo-server
> > ```
> > env:
> >         - name: VAULT_ADDR 
> >           value: "https://VaultADD"
> >         - name: VAULT_TOKEN
> >           value: "myVaultToken"
> >         - name: HELM_SECRETS_DRIVER
> >           value: "vault"  
> > ```
> > 
> > 
> > But seems not works
> > I confirm the VAULT_ADDR and VAULT_TOKEN are work correctly in my local
> > Error
> > ```
> >  failed exit status 1: [helm-sops] Error: failed to decrypt secret file 'secrets.yaml': No keys found in file
> > ```
> 
> Honestly, we dont use helm secrets a lot these days since the deprecation, plus the secret is written to the fs
> 
> We prefer to rely on helm sops that is basically supporting lot of things (gpg, kms, vault...). You have the example on how we use helm sops above ;) with projected volume
> 
> https://github.com/mozilla/sops#encrypting-using-hashicorp-vault

Ya ...

I know the example of this **argocd-repo-server-wrapper** is for gpg key 

```
#! /bin/sh

GPG_PRIVATE_KEY_FILE='/app/config/gpg/privkey.asc'

if [ -f "${GPG_PRIVATE_KEY_FILE}" ]
then
	gpg --import "${GPG_PRIVATE_KEY_FILE}"
fi

exec "$(dirname "$0")/_$(basename "$0")" "$@"
```


But what i need to do for Vault ?

I try adding in  **argocd-repo-server-wrapper**  and rebuild the image 

```
#! /bin/sh
export VAULT_ADDR="https://xxxxxxx"
export VAULT_TOKEN=$(cat /app/config/vault/vault-token) #This value from volume mount and secret

GPG_PRIVATE_KEY_FILE='/app/config/gpg/privkey.asc'

if [ -f "${GPG_PRIVATE_KEY_FILE}" ]
then
	gpg --import "${GPG_PRIVATE_KEY_FILE}"
fi

exec "$(dirname "$0")/_$(basename "$0")" "$@"
```

and mount the secret volume to  /app/config/vault/vault-token

But it turn out 

Error: failed to decrypt secret file 'secrets.yaml': No keys found in file

**Comment by tanandy** [comment]
hi, i didnt test it with hc vault:

seems you are not providing the right stuff to sops.
https://github.com/mozilla/sops/blob/master/stores/stores.go#L343

Can you try first to use sops locally with hc vault to see what is missing following the doc i provided above.

if you dont succeed to use it, you could also use directy vault inside argocd with a plugin etc...

ex: https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05

**Comment by gogovan-vincentngai** [comment]
> hi, i didnt test it with hc vault:
> 
> seems you are not providing the right stuff to sops.
> https://github.com/mozilla/sops/blob/master/stores/stores.go#L343
> 
> Can you try first to use sops locally with hc vault to see what is missing following the doc i provided above.
> 
> if you dont success to use it, you could also use directy vault inside argocd with a plugin etc...
> 
> ex: https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05

Ya ...ok thanks for help for the permission anyway , at least we can use pgp right now 
So orgrinal case is already resolved , thanks again


Just for your information ...
For the Vault case 
I export below two env var for locate the vault server and vault token 
```
export VAULT_ADDR=http://xxxxx
export VAULT_TOKEN=xxxxx
```

and verfiy sops using 
```
#Encrypt
sops --in-place -e --hc-vault-transit $VAULT_SERVER/v1/sops/keys/demokey demo.yaml
#Decrypt
sops --in-place -d --hc-vault-transit $VAULT_SERVER/v1/sops/keys/demokey demo.yaml
```

Which is success to Encrypt and Decrypt locally 
For locally i just need provide that two env var

**Comment by yann-soubeyrand** [comment]
@gogovan-vincentngai I don’t know why the wrapper doesn’t have executable permission in your repository. I’ve tried to clone the repository again, and I’ve the right permissions :thinking:

@tanandy do you have the same issue?

**Comment by tanandy** [comment]
dont know, when i was using 1.8.7

i did : 

RUN cd /usr/local/bin && \
    mv argocd-repo-server _argocd-repo-server && \
    mv argocd-repo-server-wrapper argocd-repo-server && \
    chmod +x argocd-repo-server && \
so maybe yes

**Comment by yann-soubeyrand** [comment]
OK. I’m not sure how Git handles file permissions, maybe I should add this chmod +x to the Dockerfile.

**Comment by tanandy** [comment]
> OK. I’m not sure how Git handles file permissions, maybe I should add this chmod +x to the Dockerfile.

yes indeed if you want to make it works for windows docker containers also
https://docs.docker.com/engine/reference/builder/#copy (--chown)
