### ISSUE TITLE
Planned support for age ?

### ISSUE THREAD

**Issue by lucj** [camptocamp/docker-argocd#11]
Hello, this is more a request than an issue :)
Is it planned to have this image also supporting age ?

**Comment by FarnazBGH** [comment]
You can check these PR #14  current image is supporting age you need to configure your ArgoCD RepoServer properly according to the mentioned PR.

**Comment by lconsuegra** [comment]
See https://github.com/camptocamp/docker-argocd/commit/9d9623fe36e6ab9b50ee548d3ed44f014ecf65e1
